### PR TITLE
Define model for a derivation build

### LINKED ISSUE #22: [Server] Create drv path cache
One of the critical aspects of eka-ci is being able to query whether a drv was attempted before, and being able to return that value without asking nix's store db (which also doesn't record build failures).

Effectively, this should minimally look like:

```rust
struct DrvBuild {
  // This is the key for the cache
  pub drv_path: String,
  // Whether the build was successful
  pub builds_successfully: bool,
}
```

Ideally, we will likely want to also ask (this can be future work, just recording my thoughts for now):
- "what other drvs does this depend on?"
- "how to instantiate the same drv?"
- "Does this correspond with an attr path?"
- "What are the downstream drvs? If this drv fails, then all downstream drvs should inherit that status"
```rust
struct DrvBuild {
  // This is the key for the cache
  pub drv_path: String,

  // Whether the build was successful. None -> denotes the build is pending, corresponds to NULL in sql
  pub builds_successfully: Option<bool>,

  // E.g. python.pkgs.setuptools
  pub attr_path: Option<String>,

  // These are dependencies, in `nix derivation show <drv>` they are "inputDrvs".
  // These can also be referenced with `nix-store --query --reference <drv> | grep -E '\.drv$'.
  // `nix-store --query --references` will also serve up "inputSrcs" which are files that were added to the store
  //  usually by referencing a file through a raw path literal which translates to a `nix-store --add` at evaluation time.
  // There is no build with inputSrcs, they are just added to the store and addressed by their content.
  pub drv_references: Vec<String>,

  // These are "downstream drvs", which refer to this.
  // This will likely be important if we want the ability to attempt a build again, downstream drvs should be
  // notified that that a dependency is being re-attempted so they should be attempted if the rebuild was
 // was successful.
  pub drv_referrers: Vec<String>,

   // To re-create a drv on another machine, either you need to do a `nix copy` of the build closure or re-instantiate it.
  // `nix copy` is less than ideal, as this is very expensive and doesn't scale well as server host will be a single bottleneck.
  // Or, you can retain the nix expression and re-instantiate it on a remote host
  pub git_repo_commit: GitCheckout, // repo, branch, commit
  pub nix_command: NixExpression, // flake or nix 1.0 command used to create the drv
}
```

Ideally, some sample code:
```rust
  let build = DrvBuild::new("/nix/store/wx45r069h9fcnbq7i4w0bmxciap0zihc-hello-2.12.1.drv");

  // Note: `/nix/store/` is truncated, a common prefix isn't helpful
  printlin!("new drv: {}", &build.drv_path); // "new drv: wx45r069h9fcnbq7i4w0bmxciap0zihc-hello-2.12.1.drv

  GLOBAL_DRV_CACHE.insert(build.drv_path.clone(), build);

   ...
   
```

### PR DESCRIPTION
**Pull request by niklaswimmer**
Based on the proposed `DrvBuild` struct in #22.

I spend so much time thinking about the model over the past days but I was just super unsure if we are all on the same page here. Eventually, I decided that the best way to document and share my current understanding would be to just write it all out, so here we are.

The two "entrypoints" are `DrvBuildMetadata` and `DrvBuildEvent`, the rest is support. When designing these types, I mostly thought about how we will store this information in the database, so think of them more as **table definitions**. Essentially, this PR could just as well have been a SQL file with create table statements, but instead I defined the structs that will implement [`FromRow`](https://docs.rs/sqlx/latest/sqlx/trait.FromRow.html) for these tables instead.

Also includes `DrvRefs` for storing the dependency DAG in the database.

I kindly request that you take a closer look at this @jonringer so that we can be sure to be on the same page here. Everyone else is of course also welcomed to provide feedback :)

Closes #22

### CODE REVIEW

File: backend/server/src/derivation.rs [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+
+    /// Denotes the number of times this derivation has been attempted to be build.
+    ///
+    /// Note that once the build outcome of a derivation has been determined, there is no point in
+    /// trying to build the same derivation again. If it failed once, it will always fail.
+    ///
+    /// This counter is intended for cases in which the derivation build was interrupted due to
+    /// external factors (see [DrvBuildState::Interrupted]). In these situations it may make sense
+    /// to reattempt the build (depending on the interruption kind).
+    pub build_attempt: NonZero<u32>,
```
Comment (jonringer) [inline backend/server/src/derivation.rs:19]: I think we can de-normalize this a bit, and just add this to the `DrvBuildMetadata` struct, and remove the need for DrvBuildId altogether.

File: backend/server/src/derivation.rs [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+
+/// Describes the possible states a derivation build can be in.
+pub enum DrvBuildState {
+    /// Build is scheduled in a queue and has not yet started.
+    Pending,
+    /// Build is currently running.
+    Building,
+    /// Build has completed, either successfully or not.
+    Completed {
+        result: DrvBuildResult,
```
Comment (jonringer) [inline backend/server/src/derivation.rs:84]: to simplify the data model a bit
```suggestion
        was_successful: bool,
```

File: backend/server/src/derivation.rs [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+    /// Scheduler process performed a graceful shutdown and cancelled the derivation build in the
+    /// process.
+    Cancelled,
+    /// Build process died for unknown reasons, most likely a fault in the build command.
+    ProcessDeath,
+    /// Scheduler process died. The scheduler can infer that this happend by checking for
+    /// derivation builds which do not have the status [DrvBuildStatus::Completed] whilst
+    /// starting.
+    SchedulerDeath,
+}
```
Comment (jonringer) [inline backend/server/src/derivation.rs:108]: hmm, I need to think about how terminal states should be represented as well.

OOM could be thought of as a specific kind of ProcessDeath

File: backend/server/src/derivation.rs [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+
+    /// The Nix command that was used to build this derivation.
+    pub build_command: DrvBuildCommand,
+}
+
+/// Command used to build the derivation.
+pub enum DrvBuildCommand {
+    /// Nix 1.0 style command. Fields are TBD.
+    Nix1,
+}
```
Comment (jonringer) [inline backend/server/src/derivation.rs:45]: Eventually, I was thinking of allowing different "evaluation modes". But for now we can have something which has:

- Contains the nix packaging logic:
  - repo
  - commit
- Selects the right attr (similar to "legacy" hydra jobsets):
  - file
  - nix args (optional)
  - attr (e.g. `python3Packages.protobuf`)

File: backend/server/src/derivation.rs (hunk 1 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:19]: We also need it for `DrvBuildEvent` though. My thinking here was to have a single place for writing the documentation. 

Same for `DrvId`, which can additionally ensure only valid identifiers are stored in the database (its `String` is not public, so it can not be directly constructed from outside the module).

I am a big fan of utilizing Rust's typesystem this way (see also "parse don't validate").

If you however feel that this is to much, I am open to adjusting it as necessary.

Comment (niklaswimmer) [reply backend/server/src/derivation.rs:19]: Oh, right. `DrvBuildId` and `DrvId` are two different things. Ignore the second part of my reply xD

File: backend/server/src/derivation.rs (hunk 2 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:84]: I originally anticipated different data for the ok and error variants but I have since come to the realisation that doing that would make mapping the model to the database quite difficult. So I agree. We can change it back later if necessary.

File: backend/server/src/derivation.rs (hunk 3 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:108]: What do you mean by terminal states?

Yes, OOM is just process death. I encoded it separately because I thought it may be one of the more interesting reasons. I think we will probably adjust this enum as we go and figure out what kind of error states we can actually reliably catch and determine later.

File: backend/server/src/derivation.rs (hunk 4 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:45]: Yes makes sense. I think the Git repo will probably always be necessary, independent from the evaluation mode right?

Actually, does that mean that we should store both an evaluation command and a build command? Or is it enough to have one enum that denotes the "mode" and has all the information requited for both eval and build?

Complexity of this struct does not really matter btw, I plan to just store it json encoded in a single database column.

File: backend/server/src/derivation.rs (hunk 3 above)
Comment (jonringer) [reply backend/server/src/derivation.rs:108]: fair enough, until there's a beta release, I'll likely have no stability guarantees. We should be free-ish to break schemas until we settle on something reasonable.

File: backend/server/src/derivation.rs (hunk 1 above)
Comment (jonringer) [reply backend/server/src/derivation.rs:19]: > We also need it for DrvBuildEvent though. My thinking here was to have a single place for writing the documentation.

I agree, buildevent makes sense

Comment (jonringer) [reply backend/server/src/derivation.rs:19]: > We also need it for DrvBuildEvent though. My thinking here was to have a single place for writing the documentation.

I agree

File: backend/server/src/derivation.rs (hunk 3 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:108]: Sounds good

File: backend/server/src/derivation.rs (hunk 4 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs]: I expanded the `DrvBuildCommand`.

File: backend/server/src/derivation.rs (hunk 2 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs]: Decided to keep the enum as it is more expressive than a single boolean. Added some methods to it for turning it into a bool instead. See 8c3e740.

**Comment by niklaswimmer** [comment]
I am done here @jonringer :)

File: backend/server/src/derivation.rs [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+
+/// Emitted whenever a derivation build's state changes.
+#[derive(Debug)]
+pub struct DrvBuildEvent {
+    /// The derivation build this event is associated with.
+    pub build: DrvBuildId,
+
+    /// Globally monotonically increasing numeric event identifier. Use this to determine the order
+    /// of events. Events with a higher id happened after events with a lower id.
```
Comment (jonringer) [inline backend/server/src/derivation.rs:86]: what would be the value of tracking previous  builds?

I could see some value if we tracked build logs, so there was something "to learn". But just recorded that it did fail doesn't seem like much more valuable than just have a counter.

File: backend/server/src/derivation.rs [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+///
+/// Maps a derivation to all the derivations it directly depends on and vice-versa to all the
+/// derivations that directly depend on it.
+#[derive(Debug)]
+pub struct DrvRefs {
+    /// Also known as dependant or consumer.
+    pub referrer: DrvId,
+    /// Also known as dependency.
+    pub reference: DrvId,
+}
```
Comment (jonringer) [inline backend/server/src/derivation.rs:210]: I was thinking for pulling from db that we would just have:
```
references: Vec<DrvId>,
```
on the metadata object.

`referrers` probably should never be manifested in rust as they can be a combinatorial explosion of anything which refers to it (remember we are tracking many commits, branches, and repos). So on the rust side we would just call something which would just do a recursive descent and update failure status:

```rust
  // recursive query which will mark downstream builds as "dependency failed" and add drv as a foriegn key
  // so we can retain a reference to which drv in particular failed.
  db::mark_as_failed(drv).await;
```

File: backend/server/src/derivation.rs [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+    Building,
+    /// Build has completed, either successfully or not.
+    ///
+    /// True means successful, false means an error was encountered while building the derivation.
+    Completed(DrvBuildResult),
+    /// Build was interrupted before it could complete.
+    Interrupted(DrvBuildInterruptionKind),
+    /// Build depends on a derivation that is [Interrupted][DrvBuildState::Interrupted].
+    Blocked,
+}
```
Comment (jonringer) [inline backend/server/src/derivation.rs:124]: should also probably add one for "dependency failed".

Something like:
```
DependencyFailed(DrvId),
```

**Comment by jonringer** [comment]
> I am done here @jonringer :)

Just a few questions, which I probably should have commented on previously

File: backend/server/src/derivation.rs (hunk 5 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:86]: Well, we need *some* place for storing the current build state, that is for sure. There are two approaches to this:

- store the state as part of `DrvBuildMetadata`, i.e. always only store the latest state
- store the state separately, i.e. keep old states around

I opted for storing the state separately for two reasons:

- it separates the information about a derivation build that is static (`DrvBuildMetadata`) from the information that changes (`DrvBuildEvent`). This makes both of them "immutable", so you always only need to insert, never update, which is faster.
- by keeping previous events around, we essentially get a build log out of the box. This will allow us to display information about when the build was scheduled, started and so on (we could also store this in separate columns in `DrvBuildMetadata`, but then we would need even more updates). Note that this also gives us build timings *for free*.

The `event_id` column will need to be `INTEGER PRIMARY KEY AUTOINCREMENT` in the SQlite table but that allows us to retrieve a derivation build's state with a rather simple `SELECT MAX(event_id), state FROM drv_build_event WHERE build_drv = "qwpoierujiopsafuj-hello-1.1.1.drv`. Note that this only works in SQlite because it special cases aggregate selects that use `MAX` (or `MIN`) to allow non-aggregate values in the result set.

File: backend/server/src/derivation.rs (hunk 6 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:210]: > on the metadata object.

These structs really just represent the database tables in their pure form (these structs can all impl/derive sqlx's `FromRow`) and tables can not store arrays. You could of course always set this array by issuing a second select (a single joined select can not return an array) but at that point you may as well just treat it as separate operations to begin with.

> `referrers` probably should never be manifested in rust as they can be a combinatorial explosion of anything which refers to it (remember we are tracking many commits, branches, and repos).

Sure, but then we do not need the struct at all because every query to this table can be made to only return one of the two fields (`SELECT reference FROM drv_refs WHERE referrer = "qwpoeiruqwpoe-asdf.drv"`) which can always just be turned into a `Vec<DrvId>` on the rust side. The benefit of having this struct is that it makes the type of the table record nameable, so we could have something like `fn insert_ref(ref: &DrvRefs, pool: ...) -> ...`. Without the struct this function would take two `DrvId`. Also fine, I just prefer the struct variant 🤷

**Comment by niklaswimmer** [comment]
I take from your comments that we need a place to store additional information about a build outcome, such as the build log or the dependency derivation that caused this build to fail. I think something like this could work:

```
/// Additional data for a build, only present after a build ended.
struct DrvBuildStateData {
    build: DrvBuildId,
    /// Only present when build ended with `DrvBuildState::Completed` or `DrvBuildState::Interrupted`.
    log: Option<String>,
    /// Only present when build ended with `DrvBuildState::Blocked` or `DrvBuildState::DependencyFailed`.
    failed_dependency: Option<DrvId>,
}
```

File: backend/server/src/derivation.rs (hunk 5 above)
Comment (jonringer) [reply backend/server/src/derivation.rs:86]: > by keeping previous events around, we essentially get a build log out of the box.

I could see us eventually needing this, even if not for MVP. Fair enough

> The event_id column will need to be INTEGER PRIMARY KEY AUTOINCREMENT in the SQlite table

SQLite does this by default if you have `INTEGER PRIMARY KEY`. If you don't do it explicitly, it does implicitly and calls it rowid. https://sqlite.org/rowidtable.html

File: backend/server/src/derivation.rs (hunk 6 above)
Comment (jonringer) [reply backend/server/src/derivation.rs:210]: > Sure, but then we do not need the struct at all because every query to this table can be made to only return one of the two fields (SELECT reference FROM drv_refs WHERE referrer = "qwpoeiruqwpoe-asdf.drv") which can always just be turned into a Vec<DrvId> on the rust side.

This was what I was originally thinking. But I'm also not the biggest fan of doing multiple queries to instantiate a single objection.

>  The benefit of having this struct is that it makes the type of the table record nameable, so we could have something like fn insert_ref(ref: &DrvRefs, pool: ...) -> .... Without the struct this function would take two DrvId. Also fine, I just prefer the struct variant 🤷

That's fair, sure, let's try this out.

File: backend/server/src/derivation.rs (hunk 5 above)
Comment (niklaswimmer) [reply backend/server/src/derivation.rs:86]: Yes, I know. But the implicitly created id is allowed to reuse IDs, which could mess with the `MAX`.

**Comment by jonringer** [comment]
As we "explore the problem domain" we can pivot if needed. But this looks for the time being.

Thanks a lot @niklaswimmer
